version: '3'
services:
  main-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  googlesheet-service:
    build:
      context: ./services/googlesheetservice
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - main-service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sms-service:
    build:
      context: ./services/smsservice
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
      - main-service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: atlandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: may13@1993
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:

networks:
  elk:
    driver: bridge